name: dp_tools
channels:
   - bioconda
   - conda-forge
   - defaults
dependencies:
   - python=3.10 # required for in-house codebase compatibility
   - pandas
  # - samtools
   - isatools
   - multiqc
   - schema
   - tabulate # used to generate markdown tables from pandas dataframe in post processing
   - pytest
   - pip
   - pip:
     - git+https://github.com/J-81/dp_tools.git@1.0.7rc2